"""Initial schema with all models

Revision ID: 75ddfb52a6db
Revises: 
Create Date: 2026-09-26 20:44:22.804883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ddfb52a6db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_check_in', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.add_column('waitlist_entries', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('waitlist_entries', sa.Column('campaign_source', sa.String(), nullable=True))
    op.add_column('waitlist_entries', sa.Column('consent_marketing', sa.Boolean(), nullable=True))
    op.add_column('waitlist_entries', sa.Column('consent_terms', sa.Boolean(), nullable=True))
    op.add_column('waitlist_entries', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('waitlist_entries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist_entries', 'updated_at')
    op.drop_column('waitlist_entries', 'notes')
    op.drop_column('waitlist_entries', 'consent_terms')
    op.drop_column('waitlist_entries', 'consent_marketing')
    op.drop_column('waitlist_entries', 'campaign_source')
    op.drop_column('waitlist_entries', 'phone')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'last_check_in')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
